Achroni/seurat alignment qc
kids-first/kf-dev-single-cell-rna pull request #37
Opened 2023-09-19 02:58 UTC by AntoniaChroni

## Description

To update the `seurat_alignment_qc.Rmd` notebook of the `seurat_qc` step to match OpenPedCan format. This script processes only non-hashed sc/sn-RNA-Seq libraries.

Fixes # https://github.com/kids-first/kf-dev-single-cell-rna/issues/35

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

I have uploaded input/output files used here. I also uploaded the generated html report. This was run locally, so it needs to be tested in Docker.

**Test Configuration**:
* Environment: See session info in the html report.
* Test files: [CAVATICA library](https://cavatica.sbgenomics.com/u/d3b-bixu/kf-dev-single-cell-rna/tasks/951d22ae-c0f2-4449-8d2c-e583ba80816d)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [ ] I have committed any related changes to the PR

2023-09-20 17:54 UTC, dmiller15 requested changes
It would helpful if you rewrote this PR to highlight the changes you are making to the QC script. Since you renamed the file, it's extremely difficult to see what you have removed and added here.

2023-09-20 18:09 UTC, AntoniaChroni commented
@dmiller15 This has been now addressed here fdaa93d25ad342169cc69c5cd3ff04127b183df5 and 2a96527c3b4c8ac1957c509c65d9b686b083628e. Once the review is done, let's remove the existing `seurat_alignment_qc.Rmd` script and rename the `01_Seurat_QC.Rmd` to `seurat_alignment_qc.Rmd`.

2023-09-20 18:40 UTC, dmiller15 requested changes
Much easier to review 👍

2023-09-20 18:40 UTC, dmiller15 commented on scripts/01_Seurat_QC.Rmd
> -  data_path: '/path/to/10x/output/dir/filtered_feature_bc_matrix/' # path to the directory with the filtered_feature_bc_matrix
I think we need to keep these parameters around so they can be altered when running this as an Rscript

2023-09-20 18:40 UTC, dmiller15 commented on scripts/01_Seurat_QC.Rmd
> -  scooter_path: './'
same as `out_path` and `data_path`

2023-09-20 18:40 UTC, dmiller15 commented on scripts/01_Seurat_QC.Rmd
> +options(future.globals.maxSize = 30 * 1024 ^ 3)
This is 30 GB, right?

2023-09-20 18:40 UTC, dmiller15 commented on scripts/01_Seurat_QC.Rmd
> +  theme_set(theme_bw())
Library loading should be the first thing we do in any script.

2023-09-20 18:40 UTC, dmiller15 commented on scripts/01_Seurat_QC.Rmd
> +  file.path("/Users/chronia/CHOP/GitHub/kf-dev-single-cell-rna/scripts/example/results", paste0("Seurat-QC-", sample_name, "/"))
Hardcoded path. Please revert to the old approach where this can be handed in as a param.

2023-09-20 18:40 UTC, dmiller15 commented on scripts/01_Seurat_QC.Rmd
> +data_path <- file.path("/Users/chronia/CHOP/GitHub/kf-dev-single-cell-rna/scripts/example/data/pbmc_1k_v3/outs/filtered_feature_bc_matrix")
Hardcoded path. Please revert this to a param input.

2023-09-20 18:40 UTC, dmiller15 commented on scripts/01_Seurat_QC.Rmd
> +                      dev = c("png"))
why did we drop PDF?

2023-09-20 18:40 UTC, dmiller15 commented on scripts/01_Seurat_QC.Rmd
> +scooter_path <- file.path("/Users/chronia/CHOP/GitHub/scooter")
Hardcoded path. Please revert to param input.

2023-09-20 18:40 UTC, dmiller15 commented on scripts/01_Seurat_QC.Rmd
> +scratch_dir <-
Trailing whitespace.

2023-09-20 18:40 UTC, dmiller15 commented on scripts/01_Seurat_QC.Rmd
> +                             nfeatures = 2000, assay = "RNA")
Why did we switch from a param to hardcoded here?

2023-09-20 18:40 UTC, dmiller15 commented on scripts/01_Seurat_QC.Rmd
>    print(current_plot <- plot_scatter(metadata = metadata,
This line has a different indentation than the other print statements.

2023-09-20 18:40 UTC, dmiller15 commented on scripts/01_Seurat_QC.Rmd
> +saveRDS(seurat_obj, file = paste0(results_dir, "/", "seurat_obj.rds"))
we should probably have the option to give these unique names. perhaps a `output_basename` param.

2023-09-29 13:50 UTC, migbro reviewed
I think this is close to approval, just a couple questions to help what look like might be minor adjustments to the cwl tool to ensure it works with the new script

2023-09-29 13:50 UTC, migbro commented on scripts/01_Seurat_QC.Rmd
> -  nfeatures: 2000 # number of variable features to extract
To confirm, this should now be hardcoded and no longer an option a user provides? It's ok if it is, just checking for in/when we modify the tool to work with this update

2023-09-29 13:50 UTC, migbro commented on scripts/seurat_alignment_qc.Rmd
> +---
I assume once this is reviewed, this will become the script that the cwl tool calls, and the other one will be deleted, right?

2023-09-29 13:50 UTC, migbro commented on scripts/seurat_obj_filter_final.Rmd
> +---
Yuo can keep this around if you want, but Dan has implemented this as a normal Rscript

2023-09-29 17:48 UTC, AntoniaChroni commented
@migbro Let's drop `nfeatures `from the cwl wrapper tool.

I am unsure if there is an issue or not with renaming the file based on the filename. Do we need not to do that in order for the tool to work?

2023-09-29 17:50 UTC, migbro commented
Should be no problem as long as the tool exists - basically I'd drop nfeatures, totally fine, and also change `01_Seurat_QC.Rmd` to `seurat_alignment_qc.Rmd` in the cwl tool

2023-09-29 18:35 UTC, dmiller15 commented on tools/seurat_qc.cwl
> +          $include: ../scripts/seurat_alignment_qc.Rmd
The entry name needs to be updated

2023-09-29 18:36 UTC, dmiller15 approved these changes
New code looks fine. Assume these results are what you desire.

2023-09-29 20:13 UTC, migbro requested changes
I might work on it a bit again Monday, but this simply does not work on cavatica or locally. I renamed the old QC script since it had the requested changes to the new name and updated the tool I found that:
 - the params loading either has to be part of the load block or run before. Otherwise load cannot find the scooter_path
 - I see an attempt to make it flexible to read the cell ranger output dir or h5, but the `load_sample_counts_matrix` function, I assume from scooter, cannot handle h5 files so either fix that, or just make the default input the cell ranger filtered feature dir, which is totally fine. 
 - Perhaps this worked locally with you fixed paths, but if you run it anywhere else, it seems to break:
 ```
Rscript -e "rmarkdown::render('/WORK/tools/kf-dev-single-cell-rna/scripts/seurat_alignment_qc.Rmd', clean = TRUE,
      params=list(scooter_path='/scooter',
                  results_dir='TEST',
                  data_path='/WORK/volume/TEST_scRNA/pbmc_1k_v3',
                  sample_name='pbmc_1k_v3',
                  min_genes=200,
                  max_genes=6000,
                  max_mt=15,
                  normalize_method='log_norm'
                  ))"


processing file: seurat_alignment_qc.Rmd
  |......                       |  21% [read-in-data]
Quitting from lines 102-116 [read-in-data] (seurat_alignment_qc.Rmd)
Error in `load_sample_counts_matrix()`:
! dir NA does not contain matrix.mtx
Backtrace:
 1. scooter::load_sample_counts_matrix(path = data_path, sample_name = sample_name)
```
Please review, fix, and test. Let me know if you have any questions.

2023-10-05 00:49 UTC, AntoniaChroni commented
@migbro This runs locally with no problem, I double-check. The function does read the files from the `cell ranger output dir` which should look like the below:

![Screenshot 2023-10-04 at 8 47 10 PM](https://github.com/kids-first/kf-dev-single-cell-rna/assets/46328680/e88a338f-ac6e-41d8-b47d-2ca5acf6aed1)

Your error indicates that the directory you're loading doesn't contain the matrix file. In addition, `dir NA` is mentioned. I don't see this being part of the code; do you know what is this?

```
Error in `load_sample_counts_matrix()`:
! dir NA does not contain matrix.mtx
```

2023-10-05 13:59 UTC, migbro commented
@AntoniaChroni ok, yeah, I see my issue here was that I needed to give the whole CR dir, or at least preserve th efile structure with the files also being gzipped. I also noticed that in my local run:
```
├── metadata_create_pbmc_1k_v3.tsv
├── seurat_obj.rds
└── seurat_obj_raw.rds
```
These files used to be in the `Seurat-QC-pbmc_1k_v3`, now they are just outside of it in the results_dir. So, for instance, if my results_dir was `RESULTS`, `seurat_obj.rds` used to be in `RESULTS/Seurat-QC-pbmc_1k_v3/seurat_obj.rds` , now it's in `RESULTS/seurat_obj.rds` Is that intentional? If so, I just need to tweak the cwl tool to look there for the rds and not where it looks now.

2023-10-05 17:31 UTC, migbro commented
it was set as `/WORK/volume/TEST_scRNA/TEST`, after changing to `/WORK/volume/TEST_scRNA/TEST/` still the same. I noticed that before the param used to be called `out_path`, so it looks like some changes have occurred. Remind me, generally what changed and why? What was wrong with the old script?

2023-10-05 18:01 UTC, AntoniaChroni commented
It seems that the following code was deleted from the `set-dir-and-file-names` code chunk:

```
results_dir = file.path(results_dir, paste0("Create-", sample_name, "/"))

if (dir.exists(results_dir)) {
  stop(glue("output analysis dir {results_dir} already exists"))
} else {
  dir.create(results_dir)
}
```

2023-10-05 18:50 UTC, migbro approved these changes
@AntoniaChroni , ok I think this is good to go now! Just please pull the latest version, then clear out any temp/testing files and merge. Thanks!

2023-10-05 20:49 UTC, AntoniaChroni commented
Done @migbro

2023-10-06 14:43 UTC, migbro commented
The commit history is a mess - I attempted to squash it and went too far back. The code itself should be fine, but I felt it it necessary to make this comment in case someone asks, "oh no, why?!"

2023-10-06 14:43 UTC, merged