✂️ Feature add baseclip
kids-first/kf-dev-single-cell-rna pull request #55
Opened 2024-10-16 20:42 UTC by migbro

## Description

Main purpose is to address scRNA data in which cycle lengths were not properly set resulting in workflow failure. Solution was to add a tool to cut read and mate to proper lengths. Also done:
 - Added params to h5 write to be cell ranger reanalyze compatible
 - Ran `styler` to make R code style-compliant

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] https://cavatica.sbgenomics.com/u/d3b-bixu/kf-dev-single-cell-rna/tasks/c6d0fc5d-6ce6-477b-92cb-dd67f4a139cf/
- [ ] ran `cellranger reanalyze --disable-ui --id BS_9T831XDX_PR_TEST --matrix f35d303e-63e7-45d5-ad82-346af19de1e6.filtered.h5 --localcores 8 --nopreflight` in a cell ranger docker image, successfully run.
**Test Configuration**:
* Environment:
* Test files:

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have committed any related changes to the PR

2024-10-16 20:58 UTC, dmiller15 requested changes

2024-10-16 20:58 UTC, dmiller15 commented on tools/cutadapt_fixed_length.cwl
> +  fixed_length: { type: 'int[]', doc: "Shorten reads to a fixed length. Useful for specialized protocols in which the instrument will read beyond useable sequence" }
I think we should just call these something line:
- `r1_max_len`
- `r2_max_len`

The array for this makes it seem like upper and lower boundaries. It's not very clear what's going on.

2024-10-17 14:20 UTC, dmiller15 approved these changes

2024-10-17 15:04 UTC, sickler-alex approved these changes

2024-10-17 17:59 UTC, merged